apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-recommend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-recommend-service
  template:
    metadata:
      labels:
        app: go-recommend-service
    spec:
      containers:
      - name: go-recommend-service
        image: go-recommend-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: go-recommend-service
spec:
  selector:
    app: go-recommend-service
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: ClusterIP
